name: Docker build
run-name: Docker build test
on: [push]
jobs:
  Build-Docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }} && docker build . -t liatrioexercise

  Liatrio-endpoint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }} && docker build . -t liatrioexercise
      - run: docker run -d liatrioexercise
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
